version: '2'

services:
  web:
    build: .
    image: woocommerce:0.1
    volumes:
      - migrations:/opt/OpenClass/openclass/migrations
      - static_volume:/opt/woocommerceAppProject/static
      - media_volume:/opt/woocommerceAppProject/media

    networks:
      - frontend
      - backend_postgres
    depends_on:
      - "db"
    restart: on-failure
    environment:
      - PG_HOSTNAME=db

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=woocommerce
      - POSTGRES_USER=woocommerce
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend_postgres

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/woocommerceAppProject/static
      - media_volume:/opt/woocommerceAppProject/media
    depends_on:
      - web
    networks:
      - frontend
volumes:
  migrations:
  pgdata:
  static_volume:
  media_volume:

networks:
  frontend:
  backend_postgres:
