version: '2'

services:
  web:
    build: .
    image: woocommerce:0.1
    volumes:
      - static_volume:/opt/woocommerceAppProject/static
      - media_volume:/opt/woocommerceAppProject/media

    restart: on-failure
    depends_on:
      - "db"
    restart: on-failure
    environment:
      - PG_HOSTNAME=db
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=woocommerce
      - POSTGRES_USER=woocommerce
    volumes:
      - pgdata:/var/lib/postgresql/data
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/OpenClass/static
      - media_volume:/opt/OpenClass/media
    depends_on:
      - web

volumes:
  pgdata:
  static_volume:
  media_volume:
