version: '2'

services:
  web:
    build: .
    image: woocommerce:0.1
    volumes:
      - static_volume:/opt/woocommerceAppProject/static
      - media_volume:/opt/woocommerceAppProject/media

    networks:
      - nginx_network
      - database_network
    depends_on:
      - "db"
    restart: on-failure
    environment:
      - PG_HOSTNAME=db

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=woocommerce
      - POSTGRES_USER=woocommerce
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - database_network

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/woocommerceAppProject/static
      - media_volume:/opt/woocommerceAppProject/media
    depends_on:
      - web
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge

volumes:
  pgdata:
  static_volume:
  media_volume:
